### ISSUE TITLE
Support for circular references

### ISSUE THREAD

**Issue by NicholasBoll** [19majkel94/type-graphql#130]
**Describe the bug**
If a circular reference is encountered, the type system is happy, but Schema generation will fail on something like 'X is not defined'. A solution can be found: graphql/graphql-js#373

**To Reproduce**
```ts
@ObjectType()
class Foo {
  @Field()
  bar: Bar
}

@ObjectType()
class Bar {
  @Field()
  foo: Foo
}
```

**Expected behavior**
A workaround exists for graphql js by using a function for a field's resolve property. I'm not sure if the provided example should automatically work or if it should require the same work-around. I couldn't figure out how to get `type-graphql` to generate a schema correctly.

**Additional context**
What I'm trying to do is something like:
```ts
ObjectType()
export class Foo {
  /** fields */

  @Field()
  related: PagedFoo
}

@ObjectType()
export class Paged {
  @Field(() => Int)
  skip: number

  @Field(() => Int)
  take: number

  @Field(() => Int)
  total: number
}

@ObjectType()
export class PagedFoo extends Paged {
  @Field()
  items: Foo
}
```

What I get here is "PagedFoo is not defined" from the `related: PagedFoo` code. Maybe there is a better way to do this that doesn't require a circular reference.

**Comment by 19majkel94** [comment]
First of all, you need to provide an explicit type using the `type =>` syntax as described in docs:
https://19majkel94.github.io/type-graphql/docs/types-and-fields.html

![image](https://user-images.githubusercontent.com/10618781/44486677-9873f500-a654-11e8-9f45-81da2e0f909a.png)

Futhermore, in node.js ecosystem using CommonJS module resolution system, it's not possible for one class to reference another class in the same file. It's just like:
```ts
const a = b;
const b = a;
```
It won't work whatever dirty tricks you try.

But for circular references like your case with classes, you need to leverage the CommonJS (`require`) module resolution mechanism. You need to create a separate file for both of your classes and then import the related class in each file. Node.js resolution system will resolve one dependency file to empty object `{}` on module evaluation time but thanks to the lazy type annotation `@Field(type => Bar)`, during the schema generation it will be replaced by a real class, so it will work.

And it works, just look at the tests:
https://github.com/19majkel94/type-graphql/blob/70d77666cfcfc4bae825b6258dc4c92bc8b8f610/tests/functional/circular-refs.ts

**Comment by NicholasBoll** [comment]
Thanks for the quick reply. I figured the function resolution of type was for this purpose. I have also tried the the following code before posting this issue:

```ts
@ObjectType()
class Foo {
  @Field(type => Bar)
  bar: Bar
}

@ObjectType()
class Bar {
  @Field(type => Foo)
  foo: Foo
}
```

I get the same error. Is CommonJS require necessary? If I define in the same file, Typescript is happy and since classes are hoisted, the runtime is happy.

**Comment by 19majkel94** [comment]
It won't work due to how decorators work and the TypeScript reflection mechanism is designed - see the transpiled code:
http://www.typescriptlang.org/play/#src=%40ObjectType()%0D%0Aclass%20Foo%20%7B%0D%0A%20%20%40Field(type%20%3D>%20Bar)%0D%0A%20%20bar%3A%20Bar%0D%0A%7D%0D%0A%0D%0A%40ObjectType()%0D%0Aclass%20Bar%20%7B%0D%0A%20%20%40Field(type%20%3D>%20Foo)%0D%0A%20%20foo%3A%20Foo%0D%0A%7D

Even without TS type it has an runtime error:
![image](https://user-images.githubusercontent.com/10618781/44489319-7a5dc300-a65b-11e8-945c-300b8ab5cf92.png)

And it's not TypeScript nor TypeGraphQL fault - circular dependencies in JS are problematic, you can encounter the same issue when you have circular dependencies in two mongoose schemas.

**Comment by NicholasBoll** [comment]
I guess I'm confused here. Graphs can contain circular references and circular references are not a problem in JavaScript:

```js
function Foo() { return Bar }
function Bar() { return Foo }

Foo()     // ƒ Bar() { return Foo }
Foo()()   // ƒ Foo() { return Bar }
Foo()()() // ƒ Bar() { return Foo }

const a = { }
const b = { a }
a.b = b

a     // {b: {…}}
a.b   // {a: {…}}
a.b.a // {b: {…}}
```

Circular _Dependencies_ are more difficult. My example does not have circular dependencies, just circular references. The following works perfectly fine:

```ts
@ObjectType()
class Foo {
  @Field(type => [Foo])
  related: Foo[]
}
```

The object type is referencing itself without issue. I encountered this issue when I went from an array of related object of the same type (Foo in this case) to a wrapped paging object to extract extra metadata like a total count:

```ts
@ObjectType()
class Foo {
  @Field(type => String)
  id: string

  @Field(type => PagedFoo)
  related: PagedFoo
}

@ObjectType()
class PagedFoo {
  @Field(type => Int)
  total: number

  @Field(type => Foo)
  items: Foo[]
}
```

I looked at the circular dependency test, but I didn't see how it solved this use-case. Essentially the test required 3 `ObjectTypes` rather than just 2.

Is there an example of what I'm trying to accomplish? I've seen GraphQL services that support nesting. The code in this example seems perfectly reasonable.

**Comment by NicholasBoll** [comment]
The GraphQL documentation has an example of how they do it (https://graphql.org/graphql-js/type/#examples):

> When two types need to refer to each other, or a type needs to refer to itself in a field, you can use a function expression (aka a closure or a thunk) to supply the fields lazily.

```js
var AddressType = new GraphQLObjectType({
  name: 'Address',
  fields: {
    street: { type: GraphQLString },
    number: { type: GraphQLInt },
    formatted: {
      type: GraphQLString,
      resolve(obj) {
        return obj.number + ' ' + obj.street
      }
    }
  }
});

var PersonType = new GraphQLObjectType({
  name: 'Person',
  fields: () => ({
    name: { type: GraphQLString },
    bestFriend: { type: PersonType },
  })
});
```

**Comment by NicholasBoll** [comment]
I don't know too much about the internals of how `type-graphql` builds a schema, but it does look like fields are defined using a thunk/closure: https://github.com/19majkel94/type-graphql/blob/eb88c49d86460d195b56dc051553793382409e95/src/schema/schema-generator.ts#L218

**Comment by 19majkel94** [comment]
```ts
const a = { }
const b = { a }
a.b = b
```
That's exactly what CommonJS do - first it export empty object `a = { }` and after evaluation of circular dependency it goes back to the file and evaluate it too, which results in `a.b = b`. So when we use the variable lazily `type => a` or (function c() { return a}) it won't fail on runtime.

And your examples with functions and graphql-js works because their have simple references and the most important - they use `function`/`var` which means that they are hoisted to the top of the file, so no reference error happens.

When you use `const` with arrow function, it won't work:
![image](https://user-images.githubusercontent.com/10618781/44511216-110b9d80-a6b7-11e8-9073-b648094c997b.png)
![code_2018-08-23_09-28-57](https://user-images.githubusercontent.com/10618781/44511229-19fc6f00-a6b7-11e8-8d89-55ab2c6b63fa.png)

Some problem is on TypeGraphQL side - i try to call the type function to determine if it's `Type` or `[Type]`:
https://github.com/19majkel94/type-graphql/blob/master/src/helpers/findType.ts#L50-L57

And technically yes, I could fix this to make the lazy decorators doesn't complain about this but due to the way how TypeScript emit types reflection, it's not possible without switching to `any` which doesn't make sense.

```js
let Foo = class Foo {
};
tslib_1.__decorate([
    src_1.Field(type => String),
    tslib_1.__metadata("design:type", Bar)
], Foo.prototype, "bar", void 0);
Foo = tslib_1.__decorate([
    src_1.ObjectType()
], Foo);
let Bar = class Bar {
};
tslib_1.__decorate([
    src_1.Field(type => String),
    tslib_1.__metadata("design:type", Foo)
], Bar.prototype, "foo", void 0);
Bar = tslib_1.__decorate([
    src_1.ObjectType()
], Bar);
```
You can see that it calls `tslib_1.__metadata("design:type", Bar)` before the line `let Bar = class Bar` so as `let` and `const` are not hoisted, it gives us a `ReferenceError` 😉 

**Summary**:
- use `type => Bar` type annotation on fields, query and other resolver decorators
- place one class type in one file
And everything will be working! 🎉

**Comment by NicholasBoll** [comment]
Brilliant. That did solve my problem. I must have missed something simple:

```ts
// foo.type.ts
import { PagedFoo } from './paged.foo.type'

@ObjectType()
export class Foo {
  @Field(type => String)
  id: string

  @Field(type => PagedFoo)
  related: PagedFoo
}

// paged.foo.type.ts
import { Foo } from './Foo'

@ObjectType()
export class PagedFoo {
  @Field(type => Int)
  total: number

  @Field(type => Foo)
  items: Foo[]
}
```

I'm now running into a different issue where `PagedFoo` is actually extending a `BasePaged` class decorated by `ObjectType` and getting a `GraphQLError` complaining about a type mismatch. According to the docs, this should work: https://19majkel94.github.io/type-graphql/docs/interfaces-and-inheritance.html#types-inheritance. Instead I use an abstract class using `InterfaceType` and have `PagedFoo` implement it, then GraphQL validation is happy. In the case of extension, the `isTypeOf` is defined and fails validation. In the case of implements, `isTypeOf` is not defined and GraphQL validates the shape of the data. Weird.

**Comment by 19majkel94** [comment]
If you use inheritance, you have to always return an instance of that class, not a plain object. This requirements is due to the fact that one of the super classes may implement an interface, so the class implicitly implements it too, so I have to implement `isTypeOf` during schema generation. I'm not able to detect that there's no interface implementating super class during schema generation due to the limitation of current metadata storage design, it may be fixed in the future.

**Comment by gherciu** [comment]
Maybe I'm late to the party but that's how I fixed it:

I have somewhere in my app a function `registerDto`
this method registers all Dto in `tsyringe container` e.g
```
import { container } from 'tsyringe'
import { Country } from './resolvers/country/country.dto'
import { City } from './resolvers/city/city.dto'

// List of all Dto that may have circular deps, or depend on another dto
const circularDto = [Country, City]

export const registerCircularDto = () => {
  circularDto.forEach((DtoClass) => {
    container.register(`${DtoClass.name}Dto`, {
      // Using Value instead of use class, anyway we need to resolve just to what we provided
      // And when we resolve we do not want to initialize anything
      useValue: DtoClass,
    })
  })
}
```


Now in my file where I need a reference of that dto that have circular dependency with another I do this

city.ts
```
import type { CityEntity } from '@db/entities/city.entity'
import type { CountryEntity } from '@db/entities/country.entity'
import { container } from 'tsyringe'
import type { Country } from '../country/country.dto' // IMPORTANT: import as type not simple import

@ObjectType()
export class City implements CityEntity {

  @Field(() => container.resolve<Country>('CountryDto'), {
    nullable: true,
  })
  country: CountryEntity

}
```

country.ts
```
import type { CountryEntity } from '@db/entities/country.entity'
import type { CityEntity } from '@db/entities/city.entity'
import { container } from 'tsyringe'
import type { City } from '../city/city.dto' // IMPORTANT: import as type since these do not evaluate as circular in TS

@ObjectType()
export class Country implements CountryEntity {

  @Field(() => [container.resolve<City>('CityDto')], {
    nullable: true,
  })
  cities: CityEntity[]

}

```
