### ISSUE TITLE
How to properly set up constructors

### ISSUE THREAD

**Issue by j** [19majkel94/type-graphql#172]
I was using type constructors for passing in MongoDB documents.  They look like:

```typescript
import { ObjectType, Field } from 'type-graphql';
import { ObjectId } from 'mongodb';

export interface Document {
  _id: ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
}

@ObjectType()
export class DocumentType<T extends Document> {
  protected doc: T;

  constructor(doc?: T) {
    if (doc) {
      this.doc = doc;

      if (!doc.createdAt) {
        this.doc.createdAt = new Date();
      }

      if (!doc.updatedAt) {
        this.doc.updatedAt = new Date();
      }
    }
  }

  get _id(): ObjectId {
    return this.doc._id;
  }

  @Field()
  get id(): string {
    return this.doc._id.toHexString();
  }

  @Field()
  get createdAt(): Date {
    return this.doc.createdAt;
  }

  @Field()
  get updatedAt(): Date {
    return this.doc.updatedAt;
  }

  /**
   * Sets a field in the document.  Do not mutate the document
   * outside of the class.  You must youse `set()` when
   * modifying a document field value!
   */
  set<F extends keyof T>(field: F, value: T[F]): void {
    this.doc[field] = value;
  }

  document(): T {
    return this.doc;
  }
}
```

I had to make it optional because this library calls the constructor with no arguments.

What is the preferred way of constructing types?  I was about to switch to factory patterns or static factory methods in the class, but I wanted to ask here first.

**Comment by 19majkel94** [comment]
> this library calls the constructor with no arguments

Because this library can't know what do you want to receive in constructor. It treats the argument, input and object type classes like a DTO, not a model class. 

> What is the preferred way of constructing types? I was about to switch to factory patterns or static factory methods in the class, but I wanted to ask here first.

Yes, you should do the same and create a static `create` method to initialize the object with some data or maybe a service that will create it for you. 

And for mongoose and document I think that the best way would be to separate document from object type classes and just expose a mappers that will do a conversion, like `return User.fromDocument(userDocument);`.

For a more class oriented mongo experience, you can use Typegoose (mongoose way) or TypeORM (raw Mongo client way).

**Comment by 19majkel94** [comment]
Closing as it's related to #131 🔒 

> You should just don't use constructors in TypeORM entites and TypeGraphQL types - use the services pattern instead, or maybe a separate model classes with adapters to convert from entity/input type to entity/object type.

**Comment by HoangNguyen174** [comment]
hello, I apologize for commenting on the already closed and old thread but I'm not sure where to ask. I fully understand that constructor is strictly forbidden but I just want to ask what are actual issues (performance, memory usage, etc) if I redefine the constructor
