### ISSUE TITLE
Generic types support

### ISSUE THREAD

**Issue by 19majkel94** [19majkel94/type-graphql#180]
Right now we can only extend other object type, input type and args type classes. But this doesn't allow us to overwrite a property type so we can't create a truly generic types like the one used for pagination.

So, to the higher order class pattern we have to introduce `isAbstract` option that works the same way as in [resolvers inheritance](https://19majkel94.github.io/type-graphql/docs/interfaces-and-inheritance.html#resolvers-inheritance). Then we can create generic types:
```ts
export function Edge<TNodeType>(NodeType: ClassType<TNodeType>) {
  @ObjectType({ isAbstract: true })
  abstract class EdgeType {
    @Field(type => NodeType)
    node: TNodeType;
    @Field()
    cursor: string;
  }
  return EdgeType;
}
```

We can then easily extend the generic class:
```ts
@ObjectType()
export class RecipeEdge extends Edge(Recipe) {
  @Field()
  personalNotes: string;
}

@ObjectType()
export class FriendshipEdge extends Edge(User) {
  @Field()
  friendedAt: Date;
}
```

So this would generate following GraphQL type:
```graphql
type RecipeEdge {
  node: Recipe!
  cursor: String!
  personalNotes: String!
}

type FriendshipEdge {
  node: User!
  cursor: String!
  friendedAt: DateTime!
}
```

**Comment by OwenCalvin** [comment]
@19majkel94 Any progress ?

**Comment by 19majkel94** [comment]
Available in `0.17.0-beta.8` 🚀

**Comment by XBeg9** [comment]
Amazing news ;) thanks @19majkel94

**Comment by Veetaha** [comment]
@19majkel94 According to your example:

> `` @ObjectType({ name: `Paginated${TItemClass.name}Response` })``

This way you propose to generate unique names for generic types. But what if I specified another name for `TItemClass` when had decorated it with `@ObjectType('SomeOtherName')`? I would like to set the name of the generated class without having to repeat that `'SomeOtherName'` as a factory function parameter. Could you please expose a method to retrieve GraphQL name from the given class constructor that was decorated with `@ObjectType()` ?

**Comment by 19majkel94** [comment]
I'm not sure what you are referring to 😕 

You can have a function that generates a classes (no `isAbstract`, use `name` for unique type names):

```ts
function Foo(TItem) {
  @ObjectType({ name: "Foo" + TItem.name })
  class Foo {
    @Field()
	bar: string;
  }
  return Foo;
}

const FooBar = Foo(Bar);
``` 
or as a factory for base classes (`isAbstract: true`, no `name`):
```ts
function Foo(TItem) {
  @ObjectType({ isAbstract: true })
  abstract class Foo {
    @Field()
	bar: string;
  }
  return Foo;
}

@ObjectType()
class FooBar extends Foo(Bar) {}
```

**Comment by Veetaha** [comment]
@19majkel94 Sorry if I was not verbose. The version of typegraphql that I use (namely 0.16.0) exposes `ObjectType()` function with the following overloads:
```ts
function ObjectType(): ClassDecorator;
function ObjectType(options: ObjectOptions): ClassDecorator;
function ObjectType(name: string, options?: ObjectOptions): ClassDecorator;
```

Thus, if you decorate a class the following way:

```ts
@ObjectType()
class UserType { /* ... */  }
```

the generated GraphQL type name will be `type UserType { }`.

If you want to leave your TypeScript class name being `UserType` but have generated GraphQL type to be called `User` you forward a string with the name as the first parameter to `ObjectType()` that overrides the default `UserType.name` that is used when you don't specify the name explicitly.

```ts
@ObjectType('User')
class UserType { /* ... */  }
```

Now the generated GraphQL type name is `type User { }` rather than `type UserType { }`.

And when I have the following factory function (taken from your examples):
```ts
export default function PaginatedResponse<TItem>(TItemClass: ClassType<TItem>) {

  @ObjectType(`Paginated${TItemClass.name}Response`)
  class PaginatedResponseClass {
 
  }
  return PaginatedResponseClass;
}
```
I can't be sure that `TItemClass.name === respective graphql type name`.
Suppose we have the following class:
```ts
@ObjectType('Book')
class BookType { }
```
So when I do this:
```ts
const PaginatedBookResponse = PaginatedResponse(BookType);
```
The generated graphql type will be `type PaginatedBookTypeResponse {}` rather than wanted `type PaginatedBookResponse {}`.

Thus I would like a function that returns a respective GraphQL type name for a given type, so that I could correct `PaginatedResponse()` factory definition:
```ts
import { getMetadata } from 'type-graphql';
export default function PaginatedResponse<TItem>(TItemClass: ClassType<TItem>) {

  // should throw if TItemClass was not decorated with either @ObjectType() or @InputType()
  const graphqlTypeName = getMetadata(TItemClass).name;

  @ObjectType(`Paginated${graphqlTypeName}Response`)
  class PaginatedResponseClass {
 
  }
  return PaginatedResponseClass;
}
```
P.S. I don't know why you invoke `@ObjectType()` with the object that has `name` property, as my  version of `'typegraphql'` declares `ObjectOptions` with no such property, and I pass the `name` as the bare first argument.

**Comment by 19majkel94** [comment]
@Veetaha 
Your factory function may take more arguments, like:
```ts
function PaginatedResponse<TItem>(TItemClass: ClassType<TItem>, itemName: string) {}

const PaginatedBookResponse = PaginatedResponse(BookType, "Book");
```

The `TItemClass.name` is just a shortcut for the default naming.

Accessing metadata is part of the #134.

**Comment by Veetaha** [comment]
@19majkel94 As I have said in my first comment,

> I would like to set the name of the generated class without having to repeat that `'SomeOtherName'` as a factory function parameter 


Exposing some interface to access the metadata you define would be way better than reimplementing the whell. I could wrap `ObjectType()` with my custom decorator that would store the GraphQL typename along with saving it to your `MetadataStorage`, so that I could access it myself without refering to your API. Or I could just forward its name as the factory function parameter and repeat myself twice, which was the thing I wanted to avoid initially.
