### ISSUE TITLE
Resolver Parameter validation

### ISSUE THREAD

**Issue by tonyxiao** [19majkel94/type-graphql#185]
TypeGraphql provides a nice way to validate `InputType` and `ArgType`s. However, for simple query / mutations with `@Arg` params, it would be really useful if we can allow validator (like `isEmail`) to be specified in the arguments to `@Arg` decorator.

**Comment by 19majkel94** [comment]
There's no way to integrate `class-validator` as a param validator. That's why `@ArgsType` allow for declaring resolver arguments in a classy way.

So instead of declaring all things inline:
```ts
method(
  @Arg({ validate: [
    minLegth(5),
    maxLength(30),
    isAlphanumeric,
    isLowercase
  ]})
  arg: string
);
```

You can have concise syntax:
```ts
method(@Args() { arg }: MyArgs);
```

And reusable standard class with validator's decorators:
```ts
@ArgsType()
class MyArgs {
  @MinLegth(5)
  @MaxLength(30)
  @IsAlphanumeric()
  @IsLowercase()
  arg: string; 
} 
```

When #45 will be done, you would be able to create your own `@ValidateArg` decorator that will use `joi`, `validator.js` or your favorite validation library.

**Comment by 19majkel94** [comment]
Closing for housekeeping purposes 🔒 
Please track the progress of #45.

**Comment by tonyxiao** [comment]
Thanks. By the way reflect metadata does give us enough information to validate function params, though at that point the better recommendation is probably to use explicit `ArgsType` as you mentioned. And the occasional need to handle validating a single argument (say `IsEmail`) can be done in function body.
