### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by 19majkel94** [19majkel94/type-graphql#24]
# Nice website
#### Prepare the website with:
- tutorials/getting started
- advanced usage guides
- FAQ

It should support embedding markdown from `docs` on github repo.
[Docusaurus](https://github.com/facebook/docusaurus) should be a good solution.
Github.io would be a good hosting at the beginning.

**Comment by pablocarreraest** [comment]
your vision its going to be as a typeorm integration or more freely adapting more on typescript integration. So anyone can used as using other orm as well or not using at all (just for define graphql schema using typescript)

In personal opinion I love it because you can define as typeorm entity will work as type also so should this can be integrate in typeorm docs (thinking as in a future vision)
