### ISSUE TITLE
How can I defined a two-dimension array?

### ISSUE THREAD

**Issue by wZi** [19majkel94/type-graphql#277]
Hey, everybody. 
I want to get the value like [[1,2,3], [1,2,3]]. 
What should I do?
```
  @Field(() => [[Int]])
    key?: number[][];
```
It's not work!
It will report:
```
Cannot determine GraphQL output type for key
```
any advice is welcome.
Thank you!!!!

**Comment by 19majkel94** [comment]
@wZi 
https://github.com/facebook/graphql/issues/423

**Comment by 19majkel94** [comment]
Closing for a housekeeping purposes 🔒

**Comment by Almesia** [comment]
I have the same problem, I can not find a solution, how to do it?

`    @Field(() => [[Int]])
    configurationStart: number[][];

    @Field(() => [[Int]])
    configurationEnd: number[][];`

`Error: Cannot determine GraphQL output type for configurationStart`

I really need it to be an array

**Comment by 19majkel94** [comment]
@Almesia It's not possible even in GraphQL spec:
https://github.com/graphql/graphql-spec/issues/423

**Comment by wZi** [comment]
@Almesia 

hey man, my solution may be ugly, but it works.
```
import { GraphQLScalarType } from 'graphql';

export const NumberArrayScalar = new GraphQLScalarType({
    name: 'NumberArray',
    description: '',
    parseValue(value: number[]) {
        return value || [];
    },
    serialize(value: number[]) {
        return value || [];
    },
    parseLiteral(ast) {
        return ast || [];
    },
});
```
FYI

**Comment by Almesia** [comment]
Thank you 😄 That's all what i wanted

**Comment by TDiazT** [comment]
It actually is possible in the spec. 

The example in that issue is with tuples in a list (ie. `[[Int, Float]]`) which is not allowed, but the spec does allow things such as the one here : `[[Int]]`. You can try it with the reference implementation and it should work.

I was able to generate something like this as an example:

![image](https://user-images.githubusercontent.com/7966908/58667456-0ea03900-8304-11e9-9a6a-f0ce26d29390.png)

**Comment by 19majkel94** [comment]
@TDiazT 

You are right 😉 
It can be even N dimension array of the T type - I've checked the `[[[Int!]!]!]!`.
