### ISSUE TITLE
Default nullability

### ISSUE THREAD

**Issue by elie222** [19majkel94/type-graphql#297]
GraphQL schema fields are nullable by default, but using TypeGraphQL everything is required by default. Is there a way to change this default?

If I make a GQL request and a certain field is null, the server throws an error. Getting a null for that field instead of an exception seems to be far better default behaviour.

**Comment by 19majkel94** [comment]
Fields are not nullable by default because properties in TypeScript are not optional by default, so it's much more intuitive design.

Also marking `!` and `!]!` almost everything in my schema SDL drove me crazy, so I've decided that fields are not nullable by default.

With #296 the problem will be gone as you will have 1:1 sync with TS types :P

> Is there a way to change this default?

You can create a decorator alias: `const NullableField = () => Field({ nullable: true });`.
Maybe I should provide it in out of the box 🤔

**Comment by elie222** [comment]
Thanks for the response. I’m a little confused by the second paragraph.
Surely making things non nullable by default means that you have !
everywhere?

**Comment by 19majkel94** [comment]
@elie222 
```ts
class Foo {
  bar: string;
  baz: string[];
  fooBar(baz: string): string {}
}
```

```graphql
type Foo {
  bar: String!
  baz: [String!]!
  fooBar(baz: String!): String!
}
```

> I’m a little confused by the second paragraph.

I am trying to say that before TypeGraphQL I was creating GraphQL APIs using SDL and I was forgetting about placing `!` in types like string array (`[String!]!`) which was a bad developer experience for me.

**Comment by 19majkel94** [comment]
@elie222 
I think that I shouldn't force this behavior, it should be configurable with current setting as a default one, event with #45.

Will try to make this possible soon 😉

**Comment by elie222** [comment]
Thanks for the great work!

**Comment by nodkz** [comment]
@19majkel94 
Right improvement! 👍
