### ISSUE TITLE
When trying to bundle `type-graphql`, rollup gets confused. Maybe avoid export * in index files.

### ISSUE THREAD

**Issue by joonhocho** [19majkel94/type-graphql#378]
**Describe the bug**
I am trying to bundle type-graphql using rollup and its typescript plugin.
Rollup does not recognize exported values and throws error.
It's because `index.ts` is using `export *` all over the place, and rollup doesn't know how to handle it i guess.
Also, tree shaking is not working on `type-graphql` because `export *` is not very good for tree shaking.

To improve tree-shaking and bundling, `type-graphql` should have a index file with all explicitly named exports.

Try using [tstf](https://github.com/joonhocho/tstf) to automatically generate index.ts.
```
// output generated index.ts without saving
 tstf genIndex -o src/index.ts
```
```
// save generated index.ts
 tstf genIndex -o src/index.ts -w
```
It will recursively read all exports from subdirectories and generate index file. 

**To Reproduce**
Try using rollup with `type-graphql`.
Here's my `rollup.config.ts`.
```typescript
import * as builtins from 'builtin-modules';
import commonjs from 'rollup-plugin-commonjs';
import json from 'rollup-plugin-json';
import resolve from 'rollup-plugin-node-resolve';
import sourceMaps from 'rollup-plugin-sourcemaps';
import { terser } from 'rollup-plugin-terser';
import typescript from 'rollup-plugin-typescript2';

export default {
  input: 'src/index.ts',
  output: [
    {
      file: 'dist/index.cjs.js',
      format: 'cjs',
      sourcemap: true,
    },
    // {
    //   file: 'dist/index.min.cjs.js',
    //   format: 'cjs',
    //   sourcemap: true,
    // },
    {
      file: 'dist/index.es.js',
      format: 'es',
      sourcemap: true,
    },
  ],
  // Indicate here external modules you don't wanna include in your bundle (i.e.: 'lodash')
  external: builtins,
  watch: {
    include: 'src/**',
  },
  plugins: [
    json(),
    // Allow node_modules resolution, so you can use 'external' to control
    // which external modules to include in the bundle
    // must be before typescript
    resolve({
      preferBuiltins: true,
    }),
    typescript({
      useTsconfigDeclarationDir: true,
      tsconfig: 'tsconfig.module.json',
    }),
    commonjs(),
    sourceMaps(),
    terser({
      include: [/\.min\./],
    }),
  ],
};
```

**Expected behavior**
Rollup should be able to bundle `type-graphql` and also tree shake unused codes.

**Logs**
```
[!] Error: 'Field' is not exported by ../node_modules/type-graphql/dist/index.js
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module-
src/index.ts (6:9)
6: import { Field } from 'type-graphql';
Error: 'Field' is not exported by ../node_modules/type-graphql/dist/index.js
```

**Enviorment (please complete the following information):**
 - OS: Mac
 - Node: v11.10.0
 - Package version: 0.17.4
 - TypeScript version: 3.5.3

**Comment by 19majkel94** [comment]
Explicitly named exports are tedious in maintaining and I can't recursively read all exports from subdirectories because I expose only a selected things, not all internal types.

What is your use case for tree-shaking it? It makes no sense in Node.js and in browser/client you should use [the decorator shim](https://typegraphql.ml/docs/browser-usage.html). Apollo-client integration can be recommended only in React Native as the `graphql-js` dependency is heavy, as well as the `class-validator`.

**Comment by joonhocho** [comment]
Some serverless providers limit the bundle size. Zeit, for example has a bundle limit and they provide zeit/ncc that is a bundler.

**Comment by 19majkel94** [comment]
If you care about bundle size, you should strip off `class-validator` and `google-libphonenumber` that are responsible for 70% of TypeGraphQL size.

[Parcel](https://github.com/19majkel94/type-graphql/blob/0103091f903f9a38e7d94aed1be9ecf51923b6ca/examples/apollo-client/package.json#L15) and Webpack have no problems with bundling TypeGraphQL, so you should change your bundler or report an issue in rollup repo, rather than forcing changes in TypeGraphQL codebase.

**Comment by 19majkel94** [comment]
Closing for a housekeeping purposes 🔒
