### ISSUE TITLE
Support string and number args in GraphQLISODateTime.serialize

### ISSUE THREAD

**Issue by backbone87** [19majkel94/type-graphql#404]
**Is your feature request related to a problem? Please describe.**
Sometimes dates are not present as Date objects, but rather strings or numbers. Its somewhat cumbersome to convert these to Date first in order for the type-graphql date scalar to handle them.

**Describe the solution you'd like**
Accept strings, lets assume any format supported by JS Date constructor, and numbers, lets assume unix timestamp in seconds (could be msecs, but seconds is more common in data sources).

**Describe alternatives you've considered**
Create custom scalar

**Comment by 19majkel94** [comment]
You can choose only between GraphQLISODateScalar and GraphQLTimestampScalar:
https://typegraphql.ml/docs/scalars.html#date-scalars

But if it doesn't cover your needs, you can register your custom scalar:
```ts
@Field(type => MySuperFancyDateScalar)
myField!: Date;
```

Or even more convenient:
https://typegraphql.ml/docs/scalars.html#custom-scalars

```ts
const schema = await buildSchema({
  resolvers,
  scalarsMap: [{ type: Date, scalar: MySuperFancyDateScalar }],
});
```

I can't support all use cases because you might need "unix timestamp in seconds" but for others `could be msecs` or even a difference between some event in the past (delta).
