### ISSUE TITLE
Interface Inheritance Concrete References Required

### ISSUE THREAD

**Issue by tbrannam** [19majkel94/type-graphql#72]
In building types that use interface inheritance - I had issues in returning an array of [IMyInterface] - where there were more than one concrete class implementations.  

 I can simulate the same problem when running the Inteface-Inheritance example project.

If you comment out the mutations `addStudent` and `addEmployee`, and viewing the schema via `graphiql`, you can view the top level schema, but the there is a problem when selecting `persons`.

Seems that the concrete object have to be explicitly referenced 'somewhere' in the SDL in order for the `person` query to work properly.

**Comment by 19majkel94** [comment]
Yes, interfaces need to have implementations. If you don't need it, convert the interface type to object type.

I've tried the example after `comment out the mutations addStudent and addEmployee` with adding some objects to `personsRegistry` and when I run `persons` query, I got this error from `graphql-js` internals:

![image](https://user-images.githubusercontent.com/10618781/39568001-09416a24-4ec1-11e8-882e-a1ae60e8e182.png)

As you can see in the code, I'm forcing to pass the not directly referenced types:
https://github.com/19majkel94/type-graphql/blob/795c4eac36ee2a2037277888761f02b160eaa499/src/schema/schema-generator.ts#L331-L338

But because in this example both `Student` and `Employee` object types are not referenced anywhere in the code, the files are not loaded by node.js require and decorators are not evaluated, so the class is not registered in TypeGraphQL.

The easiest fix i to just import them in the resolver file:
![image](https://user-images.githubusercontent.com/10618781/39569156-a5c6ba9a-4ec4-11e8-8029-a91543f83c28.png)

The same problem would we with resolvers, so that's why I require `resolvers` property in `buildSchema` to load files and evaluate the decorators.
I'm not convinced that introducing new config property `types` or `orphanedTypes` is a good solution. It's hard for me to imagine a real project in which you have a class like `Student` but it's not referenced anywhere in the code, even in DB stuffs or others 😕

**Comment by tbrannam** [comment]
I agree that it's only a symptom of a problem that would not occur if I had implemented the code past the mocks I had implemented so far. 

Thanks for taking the time to describe the symptoms I was seeing.
