### ISSUE TITLE
Proposal: generate classes from an existing database

### ISSUE THREAD

**Issue by omatrot** [19majkel94/type-graphql#80]
Hi there, your project seems awesome.
I know that this is a huge request but being able to generate classes from an existing database would be awesome. The database would become the source of truth. What do you think ?

**Comment by 19majkel94** [comment]
TypeGraphQL is database agnostic. If you use TypeORM, you can use [typeorm-model-generator](https://github.com/Kononnable/typeorm-model-generator) to generate classes and then only place the TypeGraphQL decorators on fields, add resolvers, etc. 😉 

In my projects I prefer the entity class to be the source of truth and the database schema is kept in sync with the code by a ORM (synchronize/migrations). So do the API shape is determined by these classes using TypeGraphQL.

**Comment by omatrot** [comment]
May be we could write some code to glue together all this to have decorators placed automatically? basic resolvers generated, etc.

I did this code generation for several years in the .NET space using t4 templates and tools like Self Tracking Entities and / Trackable entities.

I worked very well and I miss this kind of tool for GraphQL/TypeScript.

 

I’l have a look at typeorm-model-generator an TypeORM.

 

If this is something that seems valuable for you, I’m happy to help.

**Comment by 19majkel94** [comment]
There is already an issue for a CLI tool - #66.
It will have support for automatic generation of CRUD resolvers from object type classes.

Placing TypeGraphQL decorators on TypeORM classes should be done manually because you don't always want to expose all the internal stuffs as well you may want to expose some additional fields not mapped to table column. And it's not easy to map types to GraphQL types like number -> Int or Float?

So the flow would be db tables -> typeorm model generator -> placing TypeORM decorators -> generating resolvers from classes 😉

**Comment by omatrot** [comment]
I would say that at least the CLI would place TypeORM by default (numver => fload) and report warnings to be reviewed.

 

Thanks for listening.

 

Kind regards,

Olivier.

**Comment by 19majkel94** [comment]
I have to think about how this should work and if it can work this way.
Placing this in #66 list 😉
