### ISSUE TITLE
add prettier

### ISSUE THREAD

**Issue by capaj** [19majkel94/type-graphql#92]
would you accept a PR to include prettier in this project?

**Comment by 19majkel94** [comment]
Prettier is in this project since the first commit 😄 
https://github.com/19majkel94/type-graphql/blob/06189043959cb99ae67ca94f3ed4bb1fbf4def4a/package.json#L19

There's no git hook because prettier has some issue with formatting decorators:
https://github.com/prettier/prettier/issues/2613

But I constantly format the code with prettier using VSCode on development, so it's not a big deal when I'm the only contributor 😉

**Comment by capaj** [comment]
oh I assumed it's not here because there is no `.prettierrc` file, maybe it would be good to add it?

**Comment by 19majkel94** [comment]
It is also available from the first commit 😆 

https://github.com/19majkel94/type-graphql/blob/06189043959cb99ae67ca94f3ed4bb1fbf4def4a/.prettierrc

**Comment by capaj** [comment]
sorry, my bad, can't believe I missed it
